---
# Tasks file for Dart for Ubuntu box.

  # Using ansible_os_family == "Debian" works also for Ubuntu.
  # Source: https://groups.google.com/forum/#!topic/ansible-project/OZPu-b17n_w

- include: dart.yml
  when: ansible_os_family == "Debian"

# - include: pub-activate.yml
#   when: ansible_os_family == "Debian"

# - include: dartium.yml
#   when: dartium_include
